name: 'invoke-action'
description: 'Invoke a GitHub Action'
author: 'dhadka@github.com'
inputs:
  action:
    required: true
    description: 'The action to run (e.g., dhadka/private-action@v1)'
  token:
    required: false
    description: 'The token used to access the action if private'
  args:
    required: false
    description: 'The arguments to pass into the action'
  sudo:
    required: false
    description: 'Use sudo on Linux and MacOS'
    default: false
  network:
    required: false
    description: 'Network sandbox, supported values include "none"'
  filesystem:
    required: false
    description: 'File system sandbox, supported values include "none", "read-only", and "overlay"'
runs:
  using: 'node12'
  pre: 'dist/pre/index.js'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: success()
