name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/print-env
          token: ${{ secrets.PAT }}
  test-network-sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/malicious-action
          token: ${{ secrets.PAT }}
          sandbox: |
            network: none
  test-args:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/check-no-diff
          token: ${{ secrets.PAT }}
          args: |
            path: foo/