name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  #build:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - run: |
  #        npm install
  #    - run: |
  #        npm run all
  test-no-pat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/print-env
  test-pat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/malicious-action
          token: ${{ secrets.PAT }}
  test-sudo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/print-env
          sudo: true
  test-network-none:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/malicious-action
          token: ${{ secrets.PAT }}
          network: none
  test-filesystem-readonly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hello world!" > foo
      - uses: ./
        with:
          action: dhadka/malicious-action
          token: ${{ secrets.PAT }}
          fileSystem: read-only
      - run: cat foo
  test-filesystem-overlay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hello world!" > foo
      - uses: ./
        with:
          action: dhadka/malicious-action
          token: ${{ secrets.PAT }}
          fileSystem: overlay
      - run: cat foo
  test-filesystem-none:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/malicious-action
          token: ${{ secrets.PAT }}
          fileSystem: none
      - run: ls -al
  test-args:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/check-no-diff
          path: foo/
  test-cache-no-sudo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir test_cache/
          dd bs=10 count=1048576 </dev/urandom > test_cache/test_file
          chmod gou= test_cache
          ls -al .
      - name: Cache folder
        uses: actions/cache@v2
        with:
          key: nosudo-${{ github.RUN_ID }}
          path: test_cache
  test-cache-with-sudo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir test_cache/
          dd bs=10 count=1048576 </dev/urandom > test_cache/test_file
          chmod gou= test_cache
          ls -al .
      - name: Cache folder
        uses: ./
        with:
          action: actions/cache
          sudo: true
          key: sudo-${{ github.RUN_ID }}
          path: test_cache
