name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  #build:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - run: |
  #        npm install
  #    - run: |
  #        npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/print-env
          token: ${{ secrets.PAT }}
  test-sudo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/print-env
          token: ${{ secrets.PAT }}
          sudo: true
  test-network-sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/malicious-action
          token: ${{ secrets.PAT }}
          sandbox: |
            network: none
  test-args:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          action: dhadka/check-no-diff
          token: ${{ secrets.PAT }}
          args: |
            path: foo/
  test-cache-no-sudo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir test_cache/
          dd bs=10 count=1048576 </dev/urandom > test_cache/test_file
          chmod gou= test_cache
          ls -al .
      - name: Cache folder
        uses: actions/cache@v2
        with:
          key: nosudo-${{ github.RUN_ID }}
          path: test_cache
  test-cache-with-sudo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir test_cache/
          dd bs=10 count=1048576 </dev/urandom > test_cache/test_file
          chmod gou= test_cache
          ls -al .
      - name: Cache folder
        uses: ./
        with:
          action: actions/cache
          sudo: true
          args: |
            key: sudo-${{ github.RUN_ID }}
            path: test_cache